## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd

import requests 

import gmaps

#import api keys

from config3 import g_key

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv(r"C:\Users\raean\OneDrive\Desktop\CLASS FOLDER\World_Weather_Analysis\Weather_Database\WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Description
0,0,Cumpas,MX,29.9833,-109.7833,90.34,13,56,14.94,broken clouds
1,1,Saint George,US,37.1041,-113.5841,87.64,9,0,18.41,clear sky
2,2,Berezovyy,RU,51.6667,135.7000,46.20,66,78,3.94,broken clouds
3,3,Avarua,CK,-21.2078,-159.7750,84.25,74,75,10.36,broken clouds
4,4,Puerto Ayora,EC,-0.7393,-90.3518,72.68,86,55,7.76,broken clouds

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 

min_temp = float(input("What is the minimum temperature you would like for your trip? "))

max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 70
What is the maximum temperature you would like for your trip? 90

In [6]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.

preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Description
1,1,Saint George,US,37.1041,-113.5841,87.64,9,0,18.41,clear sky
3,3,Avarua,CK,-21.2078,-159.7750,84.25,74,75,10.36,broken clouds
4,4,Puerto Ayora,EC,-0.7393,-90.3518,72.68,86,55,7.76,broken clouds
7,7,Maragogi,BR,-9.0122,-35.2225,77.47,78,51,12.57,broken clouds
9,9,Ariquemes,BR,-9.9133,-63.0408,73.67,78,34,2.24,scattered clouds
10,10,Carnarvon,AU,-24.8667,113.6333,70.29,58,31,14.94,scattered clouds
11,11,Atuona,PF,-9.8000,-139.0333,77.92,79,28,17.74,light rain
15,15,Nha Trang,VN,12.2500,109.1833,84.20,81,100,3.87,overcast clouds
16,16,Port Hedland,AU,-20.3167,118.5667,77.05,100,100,0.00,overcast clouds
22,22,Manaure,CO,11.7751,-72.4445,83.84,62,5,22.57,clear sky

In [7]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.isnull().count()

City_ID                223
City                   223
Country                223
Lat                    223
Lng                    223
Max Temp               223
Humidity               223
Cloudiness             223
Wind Speed             223
Weather Description    223
dtype: int64

In [8]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.

clean_df = preferred_cities_df.dropna()

clean_df.isnull().sum()

City_ID                0
City                   0
Country                0
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Weather Description    0
dtype: int64

In [9]:
# Configure gmaps
gmaps.configure(api_key=g_key)

In [10]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.  

hotel_df = clean_df[["City", "Country","Max Temp", "Weather Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Weather Description,Lat,Lng,Hotel Name
1,Saint George,US,87.64,clear sky,37.1041,-113.5841,
3,Avarua,CK,84.25,broken clouds,-21.2078,-159.7750,
4,Puerto Ayora,EC,72.68,broken clouds,-0.7393,-90.3518,
7,Maragogi,BR,77.47,broken clouds,-9.0122,-35.2225,
9,Ariquemes,BR,73.67,scattered clouds,-9.9133,-63.0408,
10,Carnarvon,AU,70.29,scattered clouds,-24.8667,113.6333,
11,Atuona,PF,77.92,light rain,-9.8000,-139.0333,
15,Nha Trang,VN,84.20,overcast clouds,12.2500,109.1833,
16,Port Hedland,AU,77.05,overcast clouds,-20.3167,118.5667,
22,Manaure,CO,83.84,clear sky,11.7751,-72.4445,

In [11]:
# 6a. Set parameters to search for hotels with 5000 meters.



# 6b. Iterate through the hotel DataFrame.

for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame

  
    lat = row["Lat"]
    lng = row["Lng"]



    params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key,
    "location": f"{lat},{lng}"}  
  
 
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search.
    
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    
    try:
        hotel_df.loc[index, 'Hotel Name'] = hotels['results'][0]['name']
    
    except (IndexError):
    
        print("Hotel not found... skipping.")
    
hotel_df.head()

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

,City,Country,Max Temp,Weather Description,Lat,Lng,Hotel Name
1,Saint George,US,87.64,clear sky,37.1041,-113.5841,Best Western Plus Abbey Inn
3,Avarua,CK,84.25,broken clouds,-21.2078,-159.7750,Paradise Inn
4,Puerto Ayora,EC,72.68,broken clouds,-0.7393,-90.3518,Finch Bay Galapagos Hotel
7,Maragogi,BR,77.47,broken clouds,-9.0122,-35.2225,Salinas do Maragogi All Inclusive Resort
9,Ariquemes,BR,73.67,scattered clouds,-9.9133,-63.0408,Hotel Sol Nascente - Ariquemes - RO

In [12]:
# 7. Drop the rows where there is no Hotel Name.

clean_hotel_df = hotel_df.dropna()

In [13]:
# 8a. Create the output File (CSV)

output_data_file = "WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv

clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [14]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd></dd>
<dt>Current Weather</dt><dd>{Weather Description} and {Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.

hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.

location = clean_hotel_df[["Lat", "Lng"]]

In [15]:
# Add a heatmap of temperature for the vacation spots and marker for each city.

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(location)

fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

AttributeError: module 'collections' has no attribute 'Iterable'